# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"

  loaders:
    flysystem_loader:
      flysystem:
        filesystem_service: oneup_flysystem.public_uploads_filesystem_filesystem

  #set flysystem als defautl loader
  data_loader: flysystem_loader

  resolvers:
    flysystem_resolver:
      flysystem:
        filesystem_service: oneup_flysystem.public_uploads_filesystem_filesystem
        root_url: "%uploads_base_url%"
        cache_prefix: media/cache

  cache: flysystem_resolver

  filter_sets:
    thumbnail_small:
      filters:
        thumbnail:
          quality: 75
          size: [200, 200]
          mode: outbound
          allow_upscale: true

    thumbnail_medium:
      filters:
        thumbnail:
          quality: 50
          size: [600, 600]
          mode: outbound
          allow_upscale: true
